version: '3.8'

services:
  influxdb:
    image: influxdb:1.8-alpine
    container_name: influxdb
    ports:
      - "8086:8086"
      - "8082:8082"
      - "8089:8089/udp"
    volumes:
      - ./influxdb/data:/var/lib/influxdb:Z
      - ./influxdb/config/:/etc/influxdb/:Z
    environment:
      - INFLUXDB_DB=telegraf
      - INFLUXDB_ADMIN_USER=admin
      - INFLUXDB_ADMIN_PASSWORD=admin

  telegraf:
    image: telegraf:1.19-alpine
    container_name: telegraf
    privileged: true
    environment:
      HOSTNAME: "telegraf-getting-started"
    volumes:
      - ./telegraf/telegraf.conf:/etc/telegraf/telegraf.conf:Z
      - /var/run/docker.sock:/var/run/docker.sock:Z
    depends_on:
      - influxdb

  kapacitor:
    image: kapacitor:1.5-alpine
    container_name: kapacitor
    ports:
      - "9092:9092"
    volumes:
      - ./kapacitor/data/:/var/lib/kapacitor:Z
      - ./kapacitor/config/:/etc/kapacitor/:Z
    depends_on:
      - influxdb

  chronograf:
    image: chronograf:1.8-alpine
    container_name: chronograf
    ports:
      - "8888:8888"
    volumes:
      - ./chronograf/data/:/var/lib/chronograf/:Z
    environment:
      - INFLUXDB_URL=http://influxdb:8086
      - KAPACITOR_URL=http://kapacitor:9092
    depends_on:
      - influxdb
      - kapacitor